export const projectsData = [
  {
    id: 1,
    title: 'Attendance Tracker',
    description: 'Web-based system with Admin/User dashboards, location-based clock-in/out, and attendance verification.',
    image: '/src/assets/images/attendance-tracker.png',
    tags: ['MERN', 'Vercel'],
    link: 'https://sai-mwan-attendance-tracker.vercel.app/',
    linkText: 'View Live',
  },
  {
    id: 2,
    title: 'TNC Car Hub',
    description: 'Modern, mobile-first car hub landing page with Tailwind utilities for rapid, maintainable styling.',
    image: '/src/assets/images/tnc-car-hub.png',
    tags: ['HTML', 'Tailwind'],
    link: 'https://tnc-car-hub-html-tailwind-project.netlify.app/',
    linkText: 'View Live',
  },
  {
    id: 3,
    title: 'Invoice Page Prototype (HTML & CSS)',
    description: 'Responsive invoice layout with clean typography and reusable structure, ready for backend integration.',
    image: '/src/assets/images/invo.png',
    tags: ['HTML', 'CSS'],
    link: 'https://invo-html-bootstrap-css-project.netlify.app/',
    linkText: 'View Live',
  },
  {
    id: 4,
    title: 'Amazon Shopping Cart',
    description: 'Interactive shopping cart with product management, cart functionality, and dynamic pricing calculations.',
    image: '/src/assets/images/amazon-project.png',
    tags: ['JavaScript', 'DOM'],
    link: 'https://github.com/Sai-Mwan-Han-Hlyan/javascript-amazon-project',
    linkText: 'View Project',
  },
  {
    id: 5,
    title: 'To-Do App (React)',
    description: 'Component-based to-do list with CRUD operations and state management using React hooks.',
    image: '/src/assets/images/react-todo.png',
    tags: ['React', 'Hooks'],
    link: 'https://github.com/Sai-Mwan-Han-Hlyan/React-todo',
    linkText: 'View Project',
  },
  {
    id: 6,
    title: 'Golf Booking App',
    description: 'Clean mobile UI with interactive booking flow presented at school hackathon.',
    image: '/src/assets/images/cimso.png',
    tags: ['Flutter', 'Dart'],
    link: 'https://github.com/Sai-Mwan-Han-Hlyan/mobile_final',
    linkText: 'View Project',
  },
]
